Feature: hide empty sections of a pattern
PatternAtlas/pattern-atlas-ui pull request #132
Opened 2022-01-18 15:34 UTC by mar-be

Signed-off-by: Marvin Bechtold <marvin.bechtold.dev@gmail.com>

2022-01-19 14:06 UTC, lharzenetter requested changes
Please add semicolons at the line ends.

2022-01-19 14:06 UTC, lharzenetter commented on src/app/core/component/markdown-content-container/markdown-pattern-sectioncontent/markdown-pattern-section-content.component.ts
> +    this.showSection = this.renderedData.length > 0
Just to ensure that there will be no NPE, maybe add ´this.showSection = this.renderedData && this.renderedData.length > 0;´

2022-01-19 14:30 UTC, salmma requested changes

2022-01-19 14:30 UTC, salmma commented on src/app/core/component/markdown-content-container/markdown-pattern-sectioncontent/markdown-pattern-section-content.component.ts
> +  showSection = true
semicolon is missing (also in line above)

2022-01-19 17:10 UTC, salmma approved these changes
LGTM

2022-01-20 08:14 UTC, lharzenetter approved these changes

2022-01-20 08:14 UTC, merged